name: Spore CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bore-erlang
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Elixir and Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.16'
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            bore-erlang/deps
            bore-erlang/_build
          key: ${{ runner.os }}-mix-${{ hashFiles('bore-erlang/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install deps
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted
      - name: Compile
        run: mix compile --warnings-as-errors
      - name: Build escript
        run: mix escript.build
      - name: Verify escript
        run: test -x ./spore && ls -l ./spore